# Generated by Django 4.2.6 on 2023-10-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('model_of_car', models.CharField(choices=[('Toyota', 'Toyota'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Lexus', 'Lexus'), ('BMW', 'BMW'), ('Subaru', 'Subrau'), ('KIA', 'KIA')], max_length=100, null=True)),
                ('cost', models.PositiveIntegerField(null=True)),
                ('year', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
