# Generated by Django 4.2.6 on 2023-10-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_of_car',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Lexus', 'Lexus'), ('BMW', 'BMW'), ('Subaru', 'Subaru'), ('KIA', 'KIA')], max_length=100, null=True),
        ),
    ]
